version: "3.9"
services:
  db:
    image: postgres
    ports:
      - '5432:5432/tcp'
    restart: always
    environment:
      POSTGRES_USER: dtgd
      POSTGRES_PASSWORD: dtgd-secret
  agent:
    build: datadog
    ports:
      - '8125:8125/udp'
      - '8126:8126/tcp'
    environment:
      - DD_APM_ENABLED=true
      - DD_TRACE_DEBUG=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=${DD_SITE:-datadoghq.com}
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
